using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Bloggsystem.Models
{
    [MetadataType(typeof(CategoryMetadata))]
    public partial class Category
    {
        // An empty class based on an original entity class autogenerated by EF. It's just here to add the class-level attribute.
    }

    /// <summary>
    /// Occasionally EF model classes tend to be automatically regenerated. In turn these regenerations tend to wipe out manually added
    /// code such as data annotations. This class is manually created and binded to the partial class above to prevent these wipe outs.
    /// </summary>
    public class CategoryMetadata
    {

        // AllowHtml has to be used with regex here to prevent HttpRequestValidationException (which cannot be catched as a common exception):
        [AllowHtml]
        [RegularExpression(@"[^<>]*$", ErrorMessage = "HTML-kod är ej tillåtet. Uteslut tecken som '<' och '>'.")]
        [Required(ErrorMessage = "Vänligen ange en kategori.")]
        [DisplayName("Kategori:")]
        public string category1 { get; set; }
    }
}