//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bloggsystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int commentID { get; set; }
        public string name { get; set; }
        public string mail { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string website { get; set; }
        public string comment1 { get; set; }
        public string answer { get; set; }
        public int entryID { get; set; }
    
        public virtual Entry Entry { get; set; }
    }
}
