using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Bloggsystem.Models
{
    [MetadataType(typeof(EntryMetadata))]
    public partial class Entry
    {
        // An empty class based on an original entity class autogenerated by EF. It's just here to add the class-level attribute.
    }

    /// <summary>
    /// Occasionally EF model classes tend to be automatically regenerated. In turn these regenerations tend to wipe out manually added
    /// code such as data annotations. This class is manually created and binded to the partial class above to prevent these wipe outs.
    /// </summary>
    public class EntryMetadata
    {

        [DisplayName("Blogginläggs-ID:")]
        public int entryID { get; set; }

        [RegularExpression(@"[^<>]*$", ErrorMessage = "HTML-kod är ej tillåtet. Uteslut tecken som '<' och '>'.")]
        [Required(ErrorMessage = "Vänligen ange en rubrik.")]
        [DisplayName("Rubrik:")]
        public string title { get; set; }

        [DataType(DataType.Date)]
        [DisplayName("Datum:")]
        public Nullable<System.DateTime> date { get; set; }

        [RegularExpression(@"[^<>]*$", ErrorMessage = "HTML-kod är ej tillåtet. Uteslut tecken som '<' och '>'.")]
        [DisplayName("Nyckelord:")]
        public string keywords { get; set; }

        [RegularExpression(@"[^<>]*$", ErrorMessage = "HTML-kod är ej tillåtet. Uteslut tecken som '<' och '>'.")]
        [DisplayName("Beskrivning:")]
        public string description { get; set; }

        [AllowHtml]
        [DataType(DataType.Html)]
        [Required(ErrorMessage = "Vänligen skriv ett inlägg.")]
        [StringLength(8000, ErrorMessage = "Inlägget kan max bestå av 8000 tecken.")]
        [DisplayName("Inlägg:")]
        public string entry1 { get; set; }

        [Required(ErrorMessage = "Vänligen ange en kategori.")]
        public int categoryID { get; set; }

    }
}