using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Bloggsystem.Models
{
    [MetadataType(typeof(UserMetadata))]
    public partial class User
    {
        // An empty class based on an original entity class autogenerated by EF. It's just here to add the class-level attribute.
    }

    /// <summary>
    /// Occasionally EF model classes tend to be automatically regenerated. In turn these regenerations tend to wipe out manually added
    /// code such as data annotations. This class is manually created and binded to the partial class above to prevent these wipe outs.
    /// </summary>
    public class UserMetadata
    {

        [RegularExpression(@"[^<>]*$", ErrorMessage = "HTML-kod är ej tillåtet. Uteslut tecken som '<' och '>'.")]
        [Required(ErrorMessage = "Vänligen ange ett användarnamn.")]
        [DisplayName("Användarnamn:")]
        public string username { get; set; }

        [RegularExpression(@"[^<>]*$", ErrorMessage = "HTML-kod är ej tillåtet. Uteslut tecken som '<' och '>'.")]
        [DisplayName("Förnamn:")]
        public string firstname { get; set; }

        [RegularExpression(@"[^<>]*$", ErrorMessage = "HTML-kod är ej tillåtet. Uteslut tecken som '<' och '>'.")]
        [DisplayName("Efternamn:")]
        public string lastname { get; set; }

        [DisplayName("Mejladress:")]
        [Required(ErrorMessage = "Vänligen ange en giltig mejladress.")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Vänligen ange en giltig mejladress.")]
        public string mail { get; set; }
    }
}